import {
  User,
  Moon,
  Bell,
  Volume2,
  Bot,
  RotateCcw,
  Headphones,
  Info,
  Sparkles,
  Flame,
  CalendarCheck,
  Scroll,
  ShoppingBag,
  Trash2,
} from 'lucide-react';

/**
 * Settings section configuration with distinct IA categories,
 * icons, colors, and live telemetry previews.
 */
export const SETTINGS_SECTIONS = [
  {
    id: 'appearance',
    title: 'Appearance & Theme',
    category: 'Display',
    description: 'Customize light, dark & glassmorphism visuals across your OS.',
    icon: Moon,
    accent: 'violet',
    glowColor: 'rgba(167, 139, 250, 0.15)',
    borderActive: 'border-violet-500/50 dark:border-violet-400/50',
    badgeColor: 'bg-violet-500/15 text-violet-700 dark:text-violet-300 border-violet-500/30',
  },
  {
    id: 'notifications',
    title: 'Alerts & Reminders',
    category: 'System',
    description: 'Schedule daily ritual prompts, habit nudges & streak alerts.',
    icon: Bell,
    accent: 'emerald',
    glowColor: 'rgba(52, 211, 153, 0.15)',
    borderActive: 'border-emerald-500/50 dark:border-emerald-400/50',
    badgeColor: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
  },
  {
    id: 'sound',
    title: 'Audio & Haptics',
    category: 'Sensory',
    description: 'Manage audio feedback sound FX and tactile vibration cues.',
    icon: Volume2,
    accent: 'amber',
    glowColor: 'rgba(245, 158, 11, 0.15)',
    borderActive: 'border-amber-500/50 dark:border-amber-400/50',
    badgeColor: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
  },
  {
    id: 'ai',
    title: 'AI Agent & Logic',
    category: 'Intelligence',
    description: 'Configure LLM reasoning provider, telemetry access & task guards.',
    icon: Bot,
    accent: 'cyan',
    glowColor: 'rgba(6, 182, 212, 0.15)',
    borderActive: 'border-cyan-500/50 dark:border-cyan-400/50',
    badgeColor: 'bg-cyan-500/15 text-cyan-700 dark:text-cyan-300 border-cyan-500/30',
  },
  {
    id: 'account',
    title: 'Account & Sanctum',
    category: 'Identity',
    description: 'Profile avatar, identity motto, email credentials & session.',
    icon: User,
    accent: 'indigo',
    glowColor: 'rgba(99, 102, 241, 0.15)',
    borderActive: 'border-indigo-500/50 dark:border-indigo-400/50',
    badgeColor: 'bg-indigo-500/15 text-indigo-700 dark:text-indigo-300 border-indigo-500/30',
  },
  {
    id: 'data-resets',
    title: 'Data & Reset Hub',
    category: 'Storage',
    description: 'Safe granular resets for progression, tasks, quests & inventory.',
    icon: RotateCcw,
    accent: 'rose',
    glowColor: 'rgba(244, 63, 94, 0.15)',
    borderActive: 'border-rose-500/50 dark:border-rose-400/50',
    badgeColor: 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
  },
  {
    id: 'feedback',
    title: 'Feedback & Support',
    category: 'Inquiries',
    description: 'Dedicated bug reporting, feature suggestions & human support.',
    icon: Headphones,
    accent: 'sky',
    glowColor: 'rgba(56, 189, 248, 0.15)',
    borderActive: 'border-sky-500/50 dark:border-sky-400/50',
    badgeColor: 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30',
  },
  {
    id: 'about',
    title: 'About Jeevan',
    category: 'Architecture',
    description: 'Engine v2.4, client architecture, telemetry state & acknowledgments.',
    icon: Info,
    accent: 'slate',
    glowColor: 'rgba(148, 163, 184, 0.12)',
    borderActive: 'border-slate-400/50 dark:border-slate-500/50',
    badgeColor: 'bg-slate-500/15 text-slate-700 dark:text-slate-300 border-slate-500/30',
  },
];

/**
 * Granular reset targets supported by backend resetSection.
 */
export const RESET_TARGETS = [
  {
    id: 'progression',
    title: 'Reset RPG Progression',
    subtitle: 'Revert level, XP, gold and attributes back to Lv. 1 baseline',
    icon: Sparkles,
    color: 'text-amber-500',
    badge: 'Safe Reset',
    willDelete: ['Character Level set to 1', 'XP set to 0 & Gold set to 0', 'Attributes reset to 5 base'],
    willPreserve: ['Habits & Dailies untouched', 'Campaign Quests untouched', 'Inventory items untouched'],
  },
  {
    id: 'habits',
    title: 'Reset Habit Momentum',
    subtitle: 'Remove all active habit routines and habit history logs',
    icon: Flame,
    color: 'text-orange-500',
    badge: 'Habits Only',
    willDelete: ['All active Habits', 'All habit completion logs & streaks'],
    willPreserve: ['Character Level & XP untouched', 'Daily rituals untouched', 'Quests & Gold untouched'],
  },
  {
    id: 'dailies',
    title: 'Reset Daily Rituals',
    subtitle: 'Clear all daily recurring tasks and completion records',
    icon: CalendarCheck,
    color: 'text-emerald-500',
    badge: 'Dailies Only',
    willDelete: ['All Daily recurring tasks', 'All daily completion check-ins'],
    willPreserve: ['Habits & streaks untouched', 'Character progression untouched', 'Quests & Gold untouched'],
  },
  {
    id: 'quests',
    title: 'Reset Campaign Quests',
    subtitle: 'Purge all campaign quests, stages, and checklist milestones',
    icon: Scroll,
    color: 'text-indigo-500',
    badge: 'Quests Only',
    willDelete: ['All active and completed Quests', 'Quest items & milestone records'],
    willPreserve: ['Habits & Dailies untouched', 'RPG Stats & Gold untouched', 'Inventory untouched'],
  },
  {
    id: 'inventory',
    title: 'Reset Inventory & Purchases',
    subtitle: 'Clear purchased rewards, items, and transaction history',
    icon: ShoppingBag,
    color: 'text-purple-500',
    badge: 'Shop Only',
    willDelete: ['All inventory items', 'Purchase transactions & receipts'],
    willPreserve: ['Custom reward catalogue definitions', 'RPG level & character stats', 'Habits & Dailies'],
  },
  {
    id: 'all',
    title: 'Full System Wipe (Everything)',
    subtitle: 'Wipe all progression, habits, dailies, quests, and inventory',
    icon: Trash2,
    color: 'text-rose-500',
    badge: 'Destructive Wipe',
    isDanger: true,
    willDelete: ['Character Level, XP, Gold & Attributes', 'All Habits, Dailies & Quests', 'All Inventory items & logs'],
    willPreserve: ['User account email & login password'],
  },
];
