/**
 * Jeevan Section Modules Registry
 *
 * Modular architecture for current and upcoming Jeevan worlds.
 * Only sections marked available: true are enterable by the user.
 */

export const SECTIONS = [
  {
    id: 'habits-study',
    title: 'Habits & Study',
    subtitle: 'Daily Quests & Knowledge Sanctum',
    description: 'Build better habits, complete daily quests, track your learning, and stay focused on your goals.',
    status: 'AVAILABLE',
    available: true,
    route: '/',
    actionLabel: 'ENTER HABITS & STUDY →',
    badge: 'ACTIVE WORLD',
    accentColor: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.45)',
    gradient: 'from-purple-900/60 via-indigo-900/40 to-[#0A071E]',
    borderClass: 'border-purple-500/50',
    tagClass: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
    iconName: 'Sparkles',
    stats: ['Habits & Dailies', 'Study Sprints', 'RPG Progression'],
  },
  {
    id: 'fitness',
    title: 'Fitness',
    subtitle: 'Physical Mastery & Vitality',
    description: 'Track workouts, fitness routines, progress, and personal performance.',
    status: 'COMING SOON',
    available: false,
    route: null,
    actionLabel: 'COMING SOON',
    badge: 'IN FORGING',
    accentColor: '#F97316',
    glowColor: 'rgba(249, 115, 22, 0.35)',
    gradient: 'from-orange-900/50 via-amber-900/30 to-[#0A071E]',
    borderClass: 'border-orange-500/30',
    tagClass: 'bg-orange-500/15 text-orange-300 border-orange-500/30',
    iconName: 'Dumbbell',
    stats: ['Workouts', 'Calisthenics', 'Strength XP'],
  },
  {
    id: 'expense',
    title: 'Expense',
    subtitle: 'Financial Discipline & Wealth',
    description: 'Track spending, UPI, cash, budgets, and your financial progress.',
    status: 'COMING SOON',
    available: false,
    route: null,
    actionLabel: 'COMING SOON',
    badge: 'IN FORGING',
    accentColor: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.35)',
    gradient: 'from-emerald-900/50 via-teal-900/30 to-[#0A071E]',
    borderClass: 'border-emerald-500/30',
    tagClass: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
    iconName: 'Wallet',
    stats: ['UPI & Cash', 'Smart Budgets', 'Gold Analytics'],
  },
  {
    id: 'goals',
    title: 'Goals',
    subtitle: 'Long-term Vision & Milestones',
    description: 'Plan meaningful goals, milestones, and long-term progress.',
    status: 'COMING SOON',
    available: false,
    route: null,
    actionLabel: 'COMING SOON',
    badge: 'IN FORGING',
    accentColor: '#3B82F6',
    glowColor: 'rgba(59, 130, 246, 0.35)',
    gradient: 'from-blue-900/50 via-indigo-900/30 to-[#0A071E]',
    borderClass: 'border-blue-500/30',
    tagClass: 'bg-blue-500/15 text-blue-300 border-blue-500/30',
    iconName: 'Target',
    stats: ['Life Milestones', 'Roadmaps', 'Vision Boards'],
  },
  {
    id: 'health',
    title: 'Health',
    subtitle: 'Holistic Wellness & Recovery',
    description: 'Organize health-related routines, wellness tracking, and personal progress.',
    status: 'COMING SOON',
    available: false,
    route: null,
    actionLabel: 'COMING SOON',
    badge: 'IN FORGING',
    accentColor: '#EC4899',
    glowColor: 'rgba(236, 72, 153, 0.35)',
    gradient: 'from-pink-900/50 via-rose-900/30 to-[#0A071E]',
    borderClass: 'border-pink-500/30',
    tagClass: 'bg-pink-500/15 text-pink-300 border-pink-500/30',
    iconName: 'Heart',
    stats: ['Sleep & Vitals', 'Nutrition', 'Mental Clarity'],
  },
  {
    id: 'productivity',
    title: 'Productivity',
    subtitle: 'Focus Sprints & Task Flow',
    description: 'Manage tasks, routines, focus sessions, and everyday productivity.',
    status: 'COMING SOON',
    available: false,
    route: null,
    actionLabel: 'COMING SOON',
    badge: 'IN FORGING',
    accentColor: '#EAB308',
    glowColor: 'rgba(234, 179, 8, 0.35)',
    gradient: 'from-yellow-900/50 via-amber-900/30 to-[#0A071E]',
    borderClass: 'border-yellow-500/30',
    tagClass: 'bg-yellow-500/15 text-yellow-300 border-yellow-500/30',
    iconName: 'CheckSquare',
    stats: ['Deep Focus', 'Task Queue', 'Daily Flow'],
  },
];
