/**
 * Jeevan Section Modules Registry
 *
 * Updated modular structure matching Jeevan's complete ecosystem:
 * - Dashboard: Everything at a glance
 * - StudySmart: Study, Exams, Skills
 * - Wellness: Habits, Fitness, Health
 * - Finance: Money, Budget, Savings
 * - Goals & Planning: Goals, Tasks, Calendar
 * - Rewards: XP, Levels, Achievements
 * - Jeevan AI: Your Personal AI Coach / Life Intelligence
 */

export const SECTIONS = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    subtitle: 'Everything at a glance',
    description: 'Your personal life operating system at a glance — progress, vital stats, focus sprint, and daily command center.',
    status: 'AVAILABLE',
    available: true,
    route: '/',
    actionLabel: 'ENTER DASHBOARD →',
    badge: 'COMMAND CENTER',
    accentColor: '#3B82F6',
    glowColor: 'rgba(59, 130, 246, 0.45)',
    gradient: 'from-blue-900/60 via-indigo-900/40 to-[#0A071E]',
    borderClass: 'border-blue-500/50',
    tagClass: 'bg-blue-500/15 text-blue-300 border-blue-500/30',
    iconName: 'LayoutDashboard',
    stats: ['Daily Rituals', 'Hero Vitals', 'Today Progress'],
  },
  {
    id: 'studysmart',
    title: 'StudySmart',
    subtitle: 'Study, Exams, Skills',
    description: 'Supercharge your learning with focused study tracking, subject mastery, exam prep, and skill milestones.',
    status: 'AVAILABLE',
    available: true,
    route: '/study',
    actionLabel: 'ENTER STUDYSMART →',
    badge: 'ACADEMIC SANCTUM',
    accentColor: '#6366F1',
    glowColor: 'rgba(99, 102, 241, 0.45)',
    gradient: 'from-indigo-900/60 via-purple-900/40 to-[#0A071E]',
    borderClass: 'border-indigo-500/50',
    tagClass: 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30',
    iconName: 'BookOpen',
    stats: ['Deep Study', 'Subject Sprints', 'Skill XP'],
  },
  {
    id: 'wellness',
    title: 'Wellness',
    subtitle: 'Habits, Fitness, Health',
    description: 'Build atomic habits, preserve health momentum, track fitness vitals, and master daily self-discipline.',
    status: 'AVAILABLE',
    available: true,
    route: '/wellness',
    actionLabel: 'ENTER WELLNESS →',
    badge: 'VITALITY ENGINE',
    accentColor: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.45)',
    gradient: 'from-emerald-900/60 via-teal-900/40 to-[#0A071E]',
    borderClass: 'border-emerald-500/50',
    tagClass: 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30',
    iconName: 'Sparkles',
    stats: ['Atomic Habits', 'Streak Momentum', 'Health Protection'],
  },
  {
    id: 'finance',
    title: 'Finance',
    subtitle: 'Money, Budget, Savings',
    description: 'Control your money, log daily spending, build smart budgets, and achieve financial freedom.',
    status: 'AVAILABLE',
    available: true,
    route: '/finance',
    actionLabel: 'ENTER FINANCE →',
    badge: 'WEALTH VAULT',
    accentColor: '#F59E0B',
    glowColor: 'rgba(245, 158, 11, 0.45)',
    gradient: 'from-amber-900/60 via-yellow-900/40 to-[#0A071E]',
    borderClass: 'border-amber-500/50',
    tagClass: 'bg-amber-500/15 text-amber-300 border-amber-500/30',
    iconName: 'Wallet',
    stats: ['Instant Expense', 'Monthly Budget', 'Spending Analytics'],
  },
  {
    id: 'goals-planning',
    title: 'Goals & Planning',
    subtitle: 'Goals, Tasks, Calendar',
    description: 'Turn long-term vision into executable milestones, prioritized quests, and balanced calendar schedules.',
    status: 'AVAILABLE',
    available: true,
    route: '/quests',
    actionLabel: 'ENTER GOALS & PLANNING →',
    badge: 'DESTINY ROADMAP',
    accentColor: '#EC4899',
    glowColor: 'rgba(236, 72, 153, 0.45)',
    gradient: 'from-pink-900/60 via-rose-900/40 to-[#0A071E]',
    borderClass: 'border-pink-500/50',
    tagClass: 'bg-pink-500/15 text-pink-300 border-pink-500/30',
    iconName: 'Target',
    stats: ['Epic Quests', 'Milestone Roadmaps', 'Daily Tasks'],
  },
  {
    id: 'rewards',
    title: 'Rewards',
    subtitle: 'XP, Levels, Achievements',
    description: 'Turn real-world progress into power. Level up your hero rank, unlock achievements, and redeem gold loot.',
    status: 'AVAILABLE',
    available: true,
    route: '/shop',
    actionLabel: 'ENTER REWARDS →',
    badge: 'POWER & LOOT',
    accentColor: '#EAB308',
    glowColor: 'rgba(234, 179, 8, 0.45)',
    gradient: 'from-yellow-900/60 via-amber-900/40 to-[#0A071E]',
    borderClass: 'border-yellow-500/50',
    tagClass: 'bg-yellow-500/15 text-yellow-300 border-yellow-500/30',
    iconName: 'Crown',
    stats: ['Level Mastery', 'Gold Loot Store', 'Battle Achievements'],
  },
  {
    id: 'jeevan-ai',
    title: 'Jeevan AI',
    subtitle: 'Your Personal AI Coach / Life Intelligence',
    description: 'Your global intelligence companion. Plan your day, analyze streak patterns, log expenses, and master your life.',
    status: 'AVAILABLE',
    available: true,
    route: '/ai',
    actionLabel: 'ACTIVATE JEEVAN AI →',
    badge: 'GLOBAL INTELLIGENCE',
    accentColor: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.55)',
    gradient: 'from-purple-900/70 via-indigo-900/50 to-[#0A071E]',
    borderClass: 'border-purple-500/60',
    tagClass: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    iconName: 'Bot',
    stats: ['Day Planning', 'Natural Language Actions', 'Ecosystem Audit'],
  },
];
